version: "3.8"

services:
  mariadb:
    image: mariadb:lts-jammy
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - 3600:3600
    networks:
      - keycloak-network
    volumes:
      - database:/var/lib/mysql

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_DOCKER_IMAGE_VERSION}
    depends_on:
      - mariadb
    command: start-dev
    container_name: keycloak
    hostname: keycloak
    ports:
      - ${KEYCLOAK_PORT}:8080
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      DB_VENDOR: mariadb
      DB_ADDR: mariadb
      DB_DATABASE: ${MARIADB_DATABASE}
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: ${MARIADB_PASSWORD}
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge

volumes:
  database:
    driver: local
