version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_DOCKER_IMAGE_VERSION}
    command: start-dev
    container_name: keycloak
    hostname: keycloak
    ports:
      - ${KEYCLOAD_PORT}:8080
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge
